#!/usr/bin/env sh

docker rm -f wxshop

if ! (docker run --name wxshop -d -p 3308:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=wxshop --restart always mariadb:10.5.8); then
  echo "Failed to start main database service"
  exit 1
fi

echo "Dev environment setup completed, enjoy please!"
